# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/sanna/PycharmProjects/Glm-Entities-Preset-tool/asGep.ui'
#
# Created: Tue Dec 14 14:21:40 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.saveTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveTab.sizePolicy().hasHeightForWidth())
        self.saveTab.setSizePolicy(sizePolicy)
        self.saveTab.setObjectName("saveTab")
        self.gridLayout = QtWidgets.QGridLayout(self.saveTab)
        self.gridLayout.setObjectName("gridLayout")
        self.entityInfogroupBox = QtWidgets.QGroupBox(self.saveTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entityInfogroupBox.sizePolicy().hasHeightForWidth())
        self.entityInfogroupBox.setSizePolicy(sizePolicy)
        self.entityInfogroupBox.setObjectName("entityInfogroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.entityInfogroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.entityIdLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.entityIdLabel.setObjectName("entityIdLabel")
        self.gridLayout_5.addWidget(self.entityIdLabel, 0, 0, 1, 1)
        self.entityIdValueLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.entityIdValueLabel.setObjectName("entityIdValueLabel")
        self.gridLayout_5.addWidget(self.entityIdValueLabel, 0, 1, 1, 1)
        self.gchaFileLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.gchaFileLabel.setObjectName("gchaFileLabel")
        self.gridLayout_5.addWidget(self.gchaFileLabel, 1, 0, 1, 1)
        self.gchaFileValueLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.gchaFileValueLabel.setObjectName("gchaFileValueLabel")
        self.gridLayout_5.addWidget(self.gchaFileValueLabel, 1, 1, 1, 1)
        self.cacheProxyLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.cacheProxyLabel.setObjectName("cacheProxyLabel")
        self.gridLayout_5.addWidget(self.cacheProxyLabel, 2, 0, 1, 1)
        self.cacheProxyValueLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.cacheProxyValueLabel.setObjectName("cacheProxyValueLabel")
        self.gridLayout_5.addWidget(self.cacheProxyValueLabel, 2, 1, 1, 1)
        self.mayaSceneLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.mayaSceneLabel.setObjectName("mayaSceneLabel")
        self.gridLayout_5.addWidget(self.mayaSceneLabel, 3, 0, 1, 1)
        self.mayaSceneValueLabel = QtWidgets.QLabel(self.entityInfogroupBox)
        self.mayaSceneValueLabel.setObjectName("mayaSceneValueLabel")
        self.gridLayout_5.addWidget(self.mayaSceneValueLabel, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.entityInfogroupBox, 0, 0, 1, 1)
        self.entityDataGroupBox = QtWidgets.QGroupBox(self.saveTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entityDataGroupBox.sizePolicy().hasHeightForWidth())
        self.entityDataGroupBox.setSizePolicy(sizePolicy)
        self.entityDataGroupBox.setObjectName("entityDataGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.entityDataGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.meshesLabel = QtWidgets.QLabel(self.entityDataGroupBox)
        self.meshesLabel.setObjectName("meshesLabel")
        self.gridLayout_4.addWidget(self.meshesLabel, 0, 0, 1, 1)
        self.shadingGroupsLabel = QtWidgets.QLabel(self.entityDataGroupBox)
        self.shadingGroupsLabel.setObjectName("shadingGroupsLabel")
        self.gridLayout_4.addWidget(self.shadingGroupsLabel, 0, 1, 1, 1)
        self.shaderAttrLabel = QtWidgets.QLabel(self.entityDataGroupBox)
        self.shaderAttrLabel.setObjectName("shaderAttrLabel")
        self.gridLayout_4.addWidget(self.shaderAttrLabel, 2, 0, 1, 1)
        self.blindDataLabel = QtWidgets.QLabel(self.entityDataGroupBox)
        self.blindDataLabel.setObjectName("blindDataLabel")
        self.gridLayout_4.addWidget(self.blindDataLabel, 2, 1, 1, 1)
        self.meshesListWidget = QtWidgets.QListWidget(self.entityDataGroupBox)
        self.meshesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.meshesListWidget.setObjectName("meshesListWidget")
        self.gridLayout_4.addWidget(self.meshesListWidget, 1, 0, 1, 1)
        self.shadingGroupsListWidget = QtWidgets.QListWidget(self.entityDataGroupBox)
        self.shadingGroupsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.shadingGroupsListWidget.setObjectName("shadingGroupsListWidget")
        self.gridLayout_4.addWidget(self.shadingGroupsListWidget, 1, 1, 1, 1)
        self.shaderAttrListWidget = QtWidgets.QListWidget(self.entityDataGroupBox)
        self.shaderAttrListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.shaderAttrListWidget.setObjectName("shaderAttrListWidget")
        self.gridLayout_4.addWidget(self.shaderAttrListWidget, 3, 0, 1, 1)
        self.blindDataListWidget = QtWidgets.QListWidget(self.entityDataGroupBox)
        self.blindDataListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.blindDataListWidget.setObjectName("blindDataListWidget")
        self.gridLayout_4.addWidget(self.blindDataListWidget, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.entityDataGroupBox, 1, 0, 1, 1)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsHorizontalLayout.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(self.saveTab)
        self.refreshButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Documents/maya/2019/scripts/as_glmEntityPreset/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon)
        self.refreshButton.setIconSize(QtCore.QSize(32, 32))
        self.refreshButton.setObjectName("refreshButton")
        self.buttonsHorizontalLayout.addWidget(self.refreshButton)
        self.saveButton = QtWidgets.QPushButton(self.saveTab)
        self.saveButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Documents/maya/2019/scripts/as_glmEntityPreset/icons/saveAs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(32, 32))
        self.saveButton.setObjectName("saveButton")
        self.buttonsHorizontalLayout.addWidget(self.saveButton)
        self.gridLayout.addLayout(self.buttonsHorizontalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.saveTab, "")
        self.loadTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadTab.sizePolicy().hasHeightForWidth())
        self.loadTab.setSizePolicy(sizePolicy)
        self.loadTab.setObjectName("loadTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.loadTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.importFlagsGroupBox = QtWidgets.QGroupBox(self.loadTab)
        self.importFlagsGroupBox.setObjectName("importFlagsGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.importFlagsGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.meshesCheckBox = QtWidgets.QCheckBox(self.importFlagsGroupBox)
        self.meshesCheckBox.setText("")
        self.meshesCheckBox.setChecked(True)
        self.meshesCheckBox.setObjectName("meshesCheckBox")
        self.gridLayout_6.addWidget(self.meshesCheckBox, 0, 1, 1, 1)
        self.blindDataCheckBox = QtWidgets.QCheckBox(self.importFlagsGroupBox)
        self.blindDataCheckBox.setEnabled(False)
        self.blindDataCheckBox.setText("")
        self.blindDataCheckBox.setChecked(True)
        self.blindDataCheckBox.setObjectName("blindDataCheckBox")
        self.gridLayout_6.addWidget(self.blindDataCheckBox, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 1, 1)
        self.shadingGroupCheckBox = QtWidgets.QCheckBox(self.importFlagsGroupBox)
        self.shadingGroupCheckBox.setEnabled(False)
        self.shadingGroupCheckBox.setText("")
        self.shadingGroupCheckBox.setChecked(True)
        self.shadingGroupCheckBox.setObjectName("shadingGroupCheckBox")
        self.gridLayout_6.addWidget(self.shadingGroupCheckBox, 1, 1, 1, 1)
        self.shaderAttrCheckBox = QtWidgets.QCheckBox(self.importFlagsGroupBox)
        self.shaderAttrCheckBox.setEnabled(True)
        self.shaderAttrCheckBox.setText("")
        self.shaderAttrCheckBox.setChecked(True)
        self.shaderAttrCheckBox.setObjectName("shaderAttrCheckBox")
        self.gridLayout_6.addWidget(self.shaderAttrCheckBox, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.importFlagsGroupBox, 1, 1, 1, 1)
        self.loadFilesGroupBox = QtWidgets.QGroupBox(self.loadTab)
        self.loadFilesGroupBox.setToolTip("")
        self.loadFilesGroupBox.setObjectName("loadFilesGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.loadFilesGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.loadFilesGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.presetFolderLineEdit = QtWidgets.QLineEdit(self.loadFilesGroupBox)
        self.presetFolderLineEdit.setObjectName("presetFolderLineEdit")
        self.horizontalLayout.addWidget(self.presetFolderLineEdit)
        self.loadPresetFolderButton = QtWidgets.QPushButton(self.loadFilesGroupBox)
        self.loadPresetFolderButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Documents/maya/2019/scripts/as_glmEntityPreset/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadPresetFolderButton.setIcon(icon2)
        self.loadPresetFolderButton.setIconSize(QtCore.QSize(32, 32))
        self.loadPresetFolderButton.setObjectName("loadPresetFolderButton")
        self.horizontalLayout.addWidget(self.loadPresetFolderButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.presetListComboBox = QtWidgets.QComboBox(self.loadFilesGroupBox)
        self.presetListComboBox.setObjectName("presetListComboBox")
        self.verticalLayout_4.addWidget(self.presetListComboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.refreshLoadButton = QtWidgets.QPushButton(self.loadFilesGroupBox)
        self.refreshLoadButton.setText("")
        self.refreshLoadButton.setIcon(icon)
        self.refreshLoadButton.setIconSize(QtCore.QSize(32, 32))
        self.refreshLoadButton.setObjectName("refreshLoadButton")
        self.horizontalLayout_4.addWidget(self.refreshLoadButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.loadFilesGroupBox)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setToolTipDuration(2)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.layoutFileLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.layoutFileLineEdit.setEnabled(False)
        self.layoutFileLineEdit.setObjectName("layoutFileLineEdit")
        self.horizontalLayout_2.addWidget(self.layoutFileLineEdit)
        self.loadLayoutFileButton = QtWidgets.QPushButton(self.groupBox)
        self.loadLayoutFileButton.setEnabled(False)
        self.loadLayoutFileButton.setText("")
        self.loadLayoutFileButton.setIcon(icon2)
        self.loadLayoutFileButton.setIconSize(QtCore.QSize(32, 32))
        self.loadLayoutFileButton.setObjectName("loadLayoutFileButton")
        self.horizontalLayout_2.addWidget(self.loadLayoutFileButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gridLayout_2.addWidget(self.loadFilesGroupBox, 0, 0, 1, 3)
        self.selectedDataGroupBox = QtWidgets.QGroupBox(self.loadTab)
        self.selectedDataGroupBox.setObjectName("selectedDataGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.selectedDataGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.selectedDataGroupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.selectedMeshesListWidget = QtWidgets.QListWidget(self.selectedDataGroupBox)
        self.selectedMeshesListWidget.setObjectName("selectedMeshesListWidget")
        self.verticalLayout_2.addWidget(self.selectedMeshesListWidget)
        self.label_6 = QtWidgets.QLabel(self.selectedDataGroupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.selectedShadingGroupListWidget = QtWidgets.QListWidget(self.selectedDataGroupBox)
        self.selectedShadingGroupListWidget.setEnabled(False)
        self.selectedShadingGroupListWidget.setObjectName("selectedShadingGroupListWidget")
        self.verticalLayout_2.addWidget(self.selectedShadingGroupListWidget)
        self.label_8 = QtWidgets.QLabel(self.selectedDataGroupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.selectedShaderAttrListWidget = QtWidgets.QListWidget(self.selectedDataGroupBox)
        self.selectedShaderAttrListWidget.setObjectName("selectedShaderAttrListWidget")
        self.verticalLayout_2.addWidget(self.selectedShaderAttrListWidget)
        self.label_10 = QtWidgets.QLabel(self.selectedDataGroupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.selectedBlindDataListWidget = QtWidgets.QListWidget(self.selectedDataGroupBox)
        self.selectedBlindDataListWidget.setEnabled(False)
        self.selectedBlindDataListWidget.setObjectName("selectedBlindDataListWidget")
        self.verticalLayout_2.addWidget(self.selectedBlindDataListWidget)
        self.gridLayout_2.addWidget(self.selectedDataGroupBox, 1, 2, 1, 1)
        self.importedDataGroupBox = QtWidgets.QGroupBox(self.loadTab)
        self.importedDataGroupBox.setObjectName("importedDataGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.importedDataGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.importedDataGroupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.xmlMeshesListWidget = QtWidgets.QListWidget(self.importedDataGroupBox)
        self.xmlMeshesListWidget.setLineWidth(1)
        self.xmlMeshesListWidget.setAlternatingRowColors(False)
        self.xmlMeshesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.xmlMeshesListWidget.setObjectName("xmlMeshesListWidget")
        self.verticalLayout.addWidget(self.xmlMeshesListWidget)
        self.label_5 = QtWidgets.QLabel(self.importedDataGroupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.xmlShadingGroupsListWidget = QtWidgets.QListWidget(self.importedDataGroupBox)
        self.xmlShadingGroupsListWidget.setEnabled(False)
        self.xmlShadingGroupsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.xmlShadingGroupsListWidget.setObjectName("xmlShadingGroupsListWidget")
        self.verticalLayout.addWidget(self.xmlShadingGroupsListWidget)
        self.label_7 = QtWidgets.QLabel(self.importedDataGroupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.xmlShaderAttrListWidget = QtWidgets.QListWidget(self.importedDataGroupBox)
        self.xmlShaderAttrListWidget.setEnabled(True)
        self.xmlShaderAttrListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.xmlShaderAttrListWidget.setObjectName("xmlShaderAttrListWidget")
        self.verticalLayout.addWidget(self.xmlShaderAttrListWidget)
        self.label_9 = QtWidgets.QLabel(self.importedDataGroupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.xmlBlindDataListWidget = QtWidgets.QListWidget(self.importedDataGroupBox)
        self.xmlBlindDataListWidget.setEnabled(False)
        self.xmlBlindDataListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.xmlBlindDataListWidget.setObjectName("xmlBlindDataListWidget")
        self.verticalLayout.addWidget(self.xmlBlindDataListWidget)
        self.gridLayout_2.addWidget(self.importedDataGroupBox, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(87, 37, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 1, 1, 1)
        self.importToLayoutButton = QtWidgets.QPushButton(self.loadTab)
        self.importToLayoutButton.setToolTip("")
        self.importToLayoutButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Documents/maya/2019/scripts/as_glmEntityPreset/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importToLayoutButton.setIcon(icon3)
        self.importToLayoutButton.setIconSize(QtCore.QSize(32, 32))
        self.importToLayoutButton.setObjectName("importToLayoutButton")
        self.gridLayout_2.addWidget(self.importToLayoutButton, 2, 2, 1, 1)
        self.tabWidget.addTab(self.loadTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.meshesCheckBox, QtCore.SIGNAL("toggled(bool)"), self.xmlMeshesListWidget.setEnabled)
        QtCore.QObject.connect(self.shadingGroupCheckBox, QtCore.SIGNAL("toggled(bool)"), self.xmlShadingGroupsListWidget.setEnabled)
        QtCore.QObject.connect(self.shaderAttrCheckBox, QtCore.SIGNAL("toggled(bool)"), self.xmlShaderAttrListWidget.setEnabled)
        QtCore.QObject.connect(self.blindDataCheckBox, QtCore.SIGNAL("toggled(bool)"), self.xmlBlindDataListWidget.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL("toggled(bool)"), self.layoutFileLineEdit.setDisabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL("toggled(bool)"), self.loadLayoutFileButton.setDisabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL("toggled(bool)"), self.label_2.setDisabled)
        QtCore.QObject.connect(self.presetFolderLineEdit, QtCore.SIGNAL("textChanged(QString)"), self.presetListComboBox.update)
        QtCore.QObject.connect(self.presetListComboBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.xmlMeshesListWidget.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "AS Glm Entity Preset", None, -1))
        self.entityInfogroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Entity Informations", None, -1))
        self.entityIdLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Entity ID:", None, -1))
        self.entityIdValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "text", None, -1))
        self.gchaFileLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Gcha File:", None, -1))
        self.gchaFileValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "text", None, -1))
        self.cacheProxyLabel.setText(QtWidgets.QApplication.translate("MainWindow", "CacheProxy node:", None, -1))
        self.cacheProxyValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "text", None, -1))
        self.mayaSceneLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Maya scene origin:", None, -1))
        self.mayaSceneValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "text", None, -1))
        self.entityDataGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Entity Data", None, -1))
        self.meshesLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Meshes:", None, -1))
        self.shadingGroupsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shading Groups:", None, -1))
        self.shaderAttrLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shaders Attributes:", None, -1))
        self.blindDataLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Blind Data:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saveTab), QtWidgets.QApplication.translate("MainWindow", "Save Entity preset", None, -1))
        self.importFlagsGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Data to Import", None, -1))
        self.loadFilesGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Entity Preset Loader Info", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Preset Folder", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Layout Options", None, -1))
        self.checkBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "test", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Load Current Entity\'s Layout", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Layout File", None, -1))
        self.selectedDataGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Selected Entity Data", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Meshes:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shading Groups:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shader Attributes:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Blind Data/ Blendshapes:", None, -1))
        self.importedDataGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Imported Entity Data", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Meshes:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shading Groups:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Shader Attributes:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "<b>Blind Data/ Blendshapes:</b>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loadTab), QtWidgets.QApplication.translate("MainWindow", "Load Entity Preset", None, -1))

